version: '3.5'
services:
  multi-threaded-selenium-scraping:  # Service name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    volumes:
      - ./config.json:/home/site/wwwroot/config.json
